config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/upload'
  post '/upload', to: "home#upload"
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :upload
  def index
  end

  def upload
    begin
      file = params[:file]
      file_name = "#{Time.now.to_i}#{rand(9000000000)}-#{file.original_filename}"
      file_path = Rails.root.join("tmp", file_name)

      File.open(file_path, "wb") {|f| f.write(file.read)}
      uploaded_url = helpers.upload_file_to_firebase file_path
      File.delete(file_path)

      render json: {
        url: uploaded_url
      }, status: 200
    rescue FirebaseConfigInvalidError => e
      puts e.backtrace
      render json: {
        error: "Firebase Config does not exist or is not in a valid format. Make sure proper path is set in config/application.rb"
      }, status: 500
    rescue DefaultBucketCannotBeFetchedError => e
      puts e.backtrace
      render json: {
        error: "Default bucket could not be fetched. Make sure you have created a default storage bucket (read the readme.md) & your account is working & the default bucket is accessible from firebase console"
      }, status: 500
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def upload_file_to_firebase file_path
    begin
      credentials = JSON.parse(Rails.application.config.firebase_credentials)

      raise unless credentials

      project_id = credentials["project_id"]

      storage = Google::Cloud::Storage.new(
        credentials: credentials,
        project_id: project_id
      )
    rescue
      raise FirebaseConfigInvalidError
    end


    begin
      bucket = storage.bucket("#{project_id}.appspot.com")
      raise unless bucket
    rescue
      raise DefaultBucketCannotBeFetchedError
    end

    file = bucket.create_file file_path.to_s, file_path.basename.to_s, acl: :public_read
    return file.url
  end
end

app/views/home/index.html.erb
<div class="flex justify-center p-4">
  <div class="sm:mt-24 flex flex-col items-center">
    <h1 class="text-center leading-snug text-2xl sm:text-3xl md:text-4xl xl:text-5xl font-black text-indigo-900">Simple Free Image Hosting Using Firebase</h1>
    <p class="mt-6 text-center text-xs md:text-sm xl:text-lg text-indigo-800 font-semibold">Upload images &amp; other static assets for free. To configure your own, <a href="https://github.com/owaiswiz/devitary" class="text-indigo-500 border-b-2 border-indigo-200 hover:border-indigo-500">click here</a>.</p>
    <div class="mt-8 sm:mt-24">
      <div class="">
        <form id="uploadFileForm" enctype="multipart/form-data" method="post">
          <input class="form-file-upload-input overflow-hidden opacity-0 absolute -z-10" type="file" name="file" id="file" value=""/ >
          <label for="file" class="border-4 border-transparent form-file-upload-label px-8 py-3 w-64 flex flex-row items-center justify-center cursor-pointer inline-block bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 hover:text-gray-800 transition-all duration-200">
            <svg class="h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M4 16L4 17C4 18.6569 5.34315 20 7 20L17 20C18.6569 20 20 18.6569 20 17L20 16M16 8L12 4M12 4L8 8M12 4L12 16" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <span class="ml-2 font-semibold text-sm tracking-wide">Choose File</span>
          </label>
        </form>
      </div>
      <button class="border-4 border-transparent upload-file-button block w-full mt-8 py-3 bg-indigo-500 text-gray-100 hover:bg-indigo-600 hover:text-gray-100 font-semibold tracking-widest shadow-lg rounded-lg transition-all duration-200 focus:outline-none focus:shadow-outline">
        <span class="loading loader block hidden"></span>
        <span class="text-sm loaded">Upload</span>
      </button>
      <div class="uploaded-click-to-copy hidden mt-16">
        <div class="text-sm tracking-wide font-semibold text-gray-600 text-center">Uploaded! Click To Copy URL</div>
        <div class='mt-4 flex shadow-none bg-gray-300 rounded-lg cursor-pointer w-full'>
          <input type="text" class="uploaded-url-input w-48 focus:outline-none focus:shadow-outline bg-gray-300 text-gray-600 p-4 text-xs font-semibold rounded-l-lg" value="" readonly />
          <button class="copy-url-to-clipboard-button px-4 bg-indigo-500 text-gray-100 hover:bg-indigo-600 hover:text-gray-100 text-sm font-semibold tracking-widest transition-all duration-200 focus:outline-none focus:shadow-outline rounded-r-lg flex-1">
            <svg class="mx-auto h-5 text-gray-300" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M8 5H6C4.89543 5 4 5.89543 4 7V19C4 20.1046 4.89543 21 6 21H16C17.1046 21 18 20.1046 18 19V18M8 5C8 6.10457 8.89543 7 10 7H12C13.1046 7 14 6.10457 14 5M8 5C8 3.89543 8.89543 3 10 3H12C13.1046 3 14 3.89543 14 5M14 5H16C17.1046 5 18 5.89543 18 7V10M20 14H10M10 14L13 11M10 14L13 17" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </button>
        </div>

      </div>
    </div>
  </div>
</div>
<div>
  <div class="absolute -z-10 max-w-lg w-2/3 bottom-0 right-0 opacity-65 transform translate-x-16">
    <%= image_tag "uploading_illustration.svg" %>
  </div>
</div>

<script>
  var inputs = document.querySelectorAll( '.form-file-upload-input' );
  Array.prototype.forEach.call(inputs, function(input) {
    var label = input.nextElementSibling,
      labelVal = label.innerHTML;

    input.addEventListener('change',function(e) {
      var fileName = e.target.value.split('\\').pop();

      if(fileName) {
        if(fileName.length > 15)
          fileName = fileName.substr(0,15) + '...'
        label.querySelector('span').innerHTML = fileName;
      }
      else
        label.innerHTML = labelVal;
    });
  });

  document.querySelector(".form-file-upload-label").addEventListener("click", function() {
    this.classList.remove("border-red-400")
    this.classList.add("border-transparent")
    document.querySelector(".uploaded-click-to-copy").classList.add('hidden')
  });

  document.querySelector(".copy-url-to-clipboard-button").addEventListener("click", function() {
    var input = document.querySelector(".uploaded-url-input")
    input.select()
    input.setSelectionRange(0,99999)
    document.execCommand("copy")
  });


  document.querySelector(".upload-file-button").addEventListener("click", function() {
    var button = this
    var loadingSpan = button.querySelector('span.loading')
    var loadedSpan = button.querySelector('span.loaded')
    var uploadedClickToCopyDiv = document.querySelector(".uploaded-click-to-copy")
    var uploadedUrlInput = document.querySelector(".uploaded-url-input")

    var disabledStateClasses = ["opacity-50", "cursor-not-allowed", "disabled"]
    if(button.classList.contains("disabled"))
      return

    if(!document.querySelector(".form-file-upload-input").value.trim()) {
      document.querySelector(".form-file-upload-label").classList.add("border-red-400")
      return
    }

    disabledStateClasses.map(c => button.classList.add(c))
    loadingSpan.classList.remove("hidden")
    loadedSpan.classList.add("hidden")

    var formData = new FormData(document.querySelector("form#uploadFileForm"));
    Rails.ajax({
      url: "<%= home_upload_path %>",
      type: "POST", 
      data: formData,
      success: function(data) {
        uploadedClickToCopyDiv.classList.remove('hidden')
        uploadedUrlInput.value = data.url
      }, 
      error: function(data) {
        alert("Error: " + data.error)
      },
      complete: function(data) {
        disabledStateClasses.map(c => button.classList.remove(c))
        loadingSpan.classList.add("hidden")
        loadedSpan.classList.remove("hidden")
      }
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>devitary</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/inter-ui@3.12.1/inter.css" type="text/css" media="all" />
    <link rel="icon" href="<%= image_path 'logo.png' %>" type="image/png" />
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1"/>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="min-h-screen font-display bg-gray-100 overflow-x-hidden">
    <%= render partial: "partials/header.html" %>
    <%= yield %>
  </body>
</html>